//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtqK22CNT2Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ptqtaikhoan
    {
        public int Ptqid { get; set; }
        public string PtqUserName { get; set; }
        public string PtqPassword { get; set; }
        public string PtqfullName { get; set; }
        public Nullable<int> PtqAge { get; set; }
        public string PtqEmail { get; set; }
        public string PtqPhone { get; set; }
        public Nullable<bool> PtqStatus { get; set; }
    }
}
