//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtqLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptqKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptqKhoa()
        {
            this.ptqSinhVien = new HashSet<ptqSinhVien>();
        }
    
        public string PtqMaKH { get; set; }
        public string PtqTenKH { get; set; }
        public Nullable<bool> PtqTranngThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptqSinhVien> ptqSinhVien { get; set; }
    }
}
