//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtqLesson09Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PtqK22CNT2Lesson09DbEntities : DbContext
    {
        public PtqK22CNT2Lesson09DbEntities()
            : base("name=PtqK22CNT2Lesson09DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ptqKhoa> ptqKhoa { get; set; }
        public virtual DbSet<ptqSinhVien> ptqSinhVien { get; set; }
    }
}
