//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtqLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptqSinhVien
    {
        public string PtqMasv { get; set; }
        public string PtqHosv { get; set; }
        public string PtqTensv { get; set; }
        public Nullable<System.DateTime> PtqNgaySinh { get; set; }
        public Nullable<bool> PtqPhai { get; set; }
        public string PtqPhone { get; set; }
        public string PtqEmail { get; set; }
        public string PtqMaKH { get; set; }
    
        public virtual ptqKhoa ptqKhoa { get; set; }
    }
}
