//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTQLesson10entity_framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtqKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PtqKhoa()
        {
            this.PtqSinhVien = new HashSet<PtqSinhVien>();
        }
    
        public string PtqMaKH { get; set; }
        public string PtqTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtqSinhVien> PtqSinhVien { get; set; }
    }
}
